apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cleanup-workflow-template
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  entrypoint: clean-up
  imagePullSecrets:
    - name: quaylogin
    - name: oc-registry-cred
  templates:
  - name: clean-up
    script:
      image: image-registry.openshift-image-registry.svc:5000/argo/opence-dev-image:latest
      securityContext:
        runAsUser: 1084
      command: [bash]
      source: |
        set -e
        ARCH=`uname -m`
        if [[ $ARCH == "x86_64" ]]
        then
          ARGO_ARCH=amd64
        elif [[ $ARCH == "s390x" ]]
        then
          ARGO_ARCH=$ARCH
        else
          ARGO_ARCH=$ARCH
        fi
        cd $HOME
        echo "----- Acquiring argocli -----"
        # Curl correct argocli based on cluster architecture
        curl -sL https://github.com/argoproj/argo-workflows/releases/download/v2.11.0/argo-linux-$ARGO_ARCH.gz -o argo-linux.gz
        # Unzip and make binary executable
        gunzip argo-linux.gz
        chmod +x argo-linux
        # Move binary to path
        mkdir -p $HOME/bin
        mv ./argo-linux $HOME/bin/argo
        PATH=$HOME/bin:$PATH
        echo "Testing out argo"
        argo list
        argo delete my-job -n dllehr
