apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  containerRuntimeExecutor: k8sapi
  executor: |
    imagePullPolicy: Always
  workflowDefaults: |
    spec:
     securityContext:
       privileged: true
