apiVersion: v1
kind: Pod
metadata:
  name: run-templateworkflow
spec:
  containers:
  - name: argo
    image: ubuntu:latest
    command:
        - /bin/sh
        - -c
        - |
          apt-get update
          apt-get install git -y
          apt-get install curl -yy
          git clone https://github.com/SiyaAmonkar/WorkflowDemo.git
          curl -sLO https://github.com/argoproj/argo/releases/download/v3.0.2/argo-linux-amd64.gz
          gunzip argo-linux-amd64.gz
          chmod +x argo-linux-amd64
          mv ./argo-linux-amd64 /usr/local/bin/argo
          argo list
          sudo cd WorkFlowDemo
          argo template create GitRepoCodeFetchWorkflowTemplate.yaml
          argo template create NotifyOnSlackWorkflowTemplate.yaml
          argo submit FetchAndNotifyWorkFlow.yaml
    resources:
      limits:
        memory: 600Mi
      requests:
        memory: 400Mi
